version: '3.9'
services:
  db_star_wars:
    image: 'mysql:latest'
    container_name: mysqldb_star_wars
    restart: always
    environment:
      MYSQL_DATABASE: db_star_wars
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      -  '3307:3306'
    expose:
      - '3307'
    networks:
      - monteiro-network
    volumes:
      - my-db_star_wars:/var/lib/mysql

volumes:
  my-db_star_wars:

networks:
  monteiro-network:
    driver: bridge