name: Coverage Badge Generator

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Coverage Badge Generator

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: jacoco-badge-generator
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          jacoco-csv-file: ./target/site/jacoco/jacoco.csv

      - name: Coverage Percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: TestNG Report
          path: target/surefire-reports/TEST-br.com.dynamodb.service.CostumerServiceTest.xml