#Esse workflow irá buildar um projeto maven utilizando restAssured como base

name: Integration Test
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven and run Test
        run: mvn test-compile org.pitest:pitest-maven.mutationCovegare

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Pitest Report
          path: target/surefire-reports/TEST-br.com.dynamodb.service.CostumerServiceTest.xml